name: Build Debian package
on:
  push:
    branches:
      - debian
  pull_request:
    branches:
      - debian
jobs:
  debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jtdor/build-deb-action@v1
        with:
          buildpackage-opts: --build=binary --no-sign

      - uses: actions/upload-artifact@v4
        with:
          path: debian/artifacts/*
